name: Windows - build

on:
  push:
    paths:
      - .github/workflows/build-game-windows.yml
      - .gitmodules
      - config/**
      - external/**
      - src/**
      - tools/**
      - CMakeLists.txt
      - CMakePresets.json
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
    env:
      BUILD_TYPE: ${{matrix.build_type}}

    steps:
    - name: Checkout code with LFS
      uses: nschloe/action-cached-lfs-checkout@v1

    - name: Reconfigure git to use HTTP authentication
      run: >
        git config --global url."https://github.com/".insteadOf
        git@github.com:

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Generate project
      shell: cmd
      working-directory: ${{github.workspace}}
      run: tools/scripter/windows/generate_vs_project.cmd

    - name: Build
      working-directory: ${{github.workspace}}/build/game
      shell: cmd
      run: cmake --build .

