name: Ubuntu - build and run unit-tests

on:
  push:
    paths:
      - .github/workflows/build-game-ubuntu.yml
      - .gitmodules
      - config/**
      - external/**
      - src/**
      - tools/**
      - CMakeLists.txt
      - CMakePresets.json
  workflow_dispatch:
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
    env:
      BUILD_TYPE: ${{matrix.build_type}}

    steps:
    - name: Checkout code with lfs
      uses: nschloe/action-cached-lfs-checkout@v1

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build/game

    - name: Reconfigure git to use HTTP authentication
      run: >
        git config --global url."https://github.com/".insteadOf
        git@github.com:

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libopusfile-dev libflac-dev libxmp-dev libfluidsynth-dev fluidsynth libwavpack-dev libmodplug-dev libssl-dev libprotobuf-dev protobuf-compiler

    - name: Install GCC
      uses: pkgxdev/setup@v2
      with:
        +: gcc@13

    - run: gcc --version

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Generate project
      shell: bash
      working-directory: ${{github.workspace}}/build/game
      env:
        CC: gcc
        CXX: g++
      run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache --preset linux-ninja

    - name: Build game
      working-directory: ${{github.workspace}}/build/game
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Run unit tests
      working-directory: ${{github.workspace}}/bin
      run: ./UnitTests

    - name: Prepare dedicated server
      working-directory: ${{github.workspace}}
      run: ./tools/package/build_and_prepare_dedicated_server.sh

    - uses: actions/upload-artifact@v4
      with:
        name: dedicated-server
        path: ./package/dedicated_server

