name: Ubuntu - check clang-format

on:
  push:
    paths:
      - .github/workflows/check-clang-format.yml
      - src/**
      - .clang-format
  workflow_dispatch:
jobs:
  run-clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '18'
          check-path: 'src'
          exclude-regex: '.*\.generated\..*'
